# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0350726a3c1264c527b40792e91fd15eb64cc0ab7c9f934d4950d5a5fc8e11753b276f65d2db12c4f9fc2edac599a89740f81975d10fad7122506a3ecb6262b

test:
  secret_key_base: 8c1d99340dc103417eda44f79e3ed43eae7b9a83c1951e133d1284e340b2a6c66c61cb985668e6b7fd7731625d4db91ce88fd4cdad06f96e21bbf97d7e6cab02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
